# Generated by Django 4.2 on 2025-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicauthorization', '0003_user_delete_clinicadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
