# Generated by Django 4.2 on 2025-06-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicauthorization', '0004_registeruser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
