# Generated by Django 4.2 on 2025-06-10 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=100)),
                ('dr_specialization', models.CharField(max_length=100)),
                ('dr_experience', models.PositiveIntegerField()),
                ('dr_availability', models.BooleanField()),
                ('dr_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
            ],
        ),
    ]
