# Generated by Django 4.2 on 2025-06-10 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('page', models.PositiveBigIntegerField()),
                ('pgender', models.CharField(max_length=15)),
                ('paddress', models.CharField(max_length=200)),
                ('pcontact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('pdate', models.DateField(auto_now_add=True)),
                ('pmed_his', models.TextField()),
                ('pcurrent_med', models.TextField()),
                ('pallergies', models.TextField()),
                ('pmedication', models.TextField()),
            ],
        ),
    ]
